### ISSUE TITLE
The first Enter press in a multiline text input does not create a new line

### ISSUE THREAD

**Issue by crazyjay97** [longbridge/gpui-component#494]
When I first focus on the Input, the first press of Enter does not produce a newline effect. During the program's lifecycle, the first press of Enter after each subsequent focus will not produce any effect.
```rust
let text_input = cx.new_view(|cx| {
    TextInput::new(cx).multi_line().rows(3).with_size(px(12.0))
});
```

**Comment by huacnlee** [comment]
I can't replay this issue. Would do please take a video for show it?

**Comment by crazyjay97** [comment]
Uploading 录屏2024-12-25 09.52.40.mov…

**Comment by crazyjay97** [comment]
https://github.com/user-attachments/assets/2e0c68ae-7e8f-479d-87a3-f37304ad2fb4

**Comment by crazyjay97** [comment]
OS: macOS Sequoia 15.0.1
actually, I had to press Enter twice to create a new line.
maybe it's an issue with my laptop
